### ISSUE TITLE
Returning Error When using `api.http.get_user_info`

### ISSUE THREAD

**Issue by NoapMat** [RFS-ADRENO/fbapy#21]
It works fine using the http method of `api.http.get_user_info` when using VPN/Proxy:
```
Cannot get MQTT endpoint
Listening to MQTT...
Connected with result code 0
```

but when i'm not using VPN/Proxy, I couldn't seem get it work:
```
Got this account's message region: PRN
Listening to MQTT...
Connected with result code 0
```

Error:
```
'NoneType' object is not subscriptable
```

My code:
```
api.http.get_user_info(
    <sender_fbid>
)
```

**Comment by RFS-ADRENO** [comment]
I will have a look into this

**Comment by RFS-ADRENO** [comment]
@NoapMat What's your OS, node version and country?

**Comment by NoapMat** [comment]
> @NoapMat What's your OS, node version and country?

Hello there, i'm on Debian. What do you mean by node version? (Are you asking my Python Version?), I'm running this on `Python 3.11.8`.

**Update**: It is working as expected i just changed my ISP's IP,  i cannot replicate it as of now, and I got no `Got this account's message region: PRN` showing when i changed ISP IP. 

Sorry, I couldn't provide logs/screenshot, and any other information about it. You could mark this as *can't reproduce*.
